name: Bug Report
description: Report a Bug of the Plugin
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: dropdown
    id: software
    attributes:
      label: Server Software
      description: What version of server software are you using?
      options:
        - Purpur
        - Paper
        - Spigot
        - different
    validations:
      required: true
  - type: input
    id: software-different
    attributes:
      label: A different Server Software
      description: Only if you have choosen the option different above!
      placeholder: Server Software
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of minecraft are you using?
      options:
        - 1.19.4
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Plugin Version
      description: What version of the plugin are you using?
      options:
        - v1.4
        - v1.4.1
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant (crash) log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
